# Generated by Django 5.1.6 on 2025-03-07 17:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_organization_options_alter_user_options'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_kudos_reset',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_kudos_reset'], name='accounts_us_last_ku_8657c3_idx'),
        ),
    ]
