# Generated by Django 5.1.6 on 2025-03-04 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kudos',
            options={'ordering': ['-id']},
        ),
    ]
