# Generated by Django 5.1.6 on 2025-03-05 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudos_app', '0002_alter_kudos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kudos',
            options={},
        ),
    ]
