# Generated by Django 5.1.6 on 2025-03-07 17:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudos_app', '0003_alter_kudos_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='kudos',
            index=models.Index(fields=['sender', 'created_at'], name='kudos_app_k_sender__fd06b1_idx'),
        ),
        migrations.AddIndex(
            model_name='kudos',
            index=models.Index(fields=['receiver', 'created_at'], name='kudos_app_k_receive_08d70e_idx'),
        ),
    ]
